#include "remotepc.h"

remotePC::remotePC(QWidget *parent)
{
    font = new QFont();
    font->setPointSize(12);

    remoteMain = new QHBoxLayout(this);
    remotePCGroup = new QGroupBox(QStringLiteral("遠端電腦"), this);
    remotePCLay = new QVBoxLayout(remotePCGroup);
    repclay_01 = new QHBoxLayout();
    repclay_02 = new QHBoxLayout();
    repclay_03 = new QHBoxLayout();
    repclay_04 = new QHBoxLayout();
    repclay_05 = new QHBoxLayout();
    repclay_06 = new QHBoxLayout();
    repclay_07 = new QHBoxLayout();
    repclay_08 = new QHBoxLayout();
    repclay_09 = new QHBoxLayout();
    repclay_10 = new QHBoxLayout();

    state = new QWidget();
    state->setStyleSheet("background-color:green;");

    remotePCLa_01 = new QLabel(QStringLiteral("IP Address:"), remotePCGroup);
    remotePCLa_02 = new QLabel(QStringLiteral("(IPAddress)"), remotePCGroup);
    remotePCLa_03 = new QLabel(QStringLiteral("CPU使用率"), remotePCGroup);
    remotePCLa_04 = new QLabel(QStringLiteral("%"), remotePCGroup);
    remotePCLa_05 = new QLabel(QStringLiteral("CPU溫度"), remotePCGroup);
    remotePCLa_06 = new QLabel(QStringLiteral("℃"), remotePCGroup);
    remotePCLa_07 = new QLabel(QStringLiteral("CPU時脈"), remotePCGroup);
    remotePCLa_08 = new QLabel(QStringLiteral("Hz"), remotePCGroup);
    remotePCLa_09 = new QLabel(QStringLiteral("GPU使用率"), remotePCGroup);
    remotePCLa_10 = new QLabel(QStringLiteral("%"), remotePCGroup);
    remotePCLa_11 = new QLabel(QStringLiteral("GPU溫度"), remotePCGroup);
    remotePCLa_12 = new QLabel(QStringLiteral("℃"), remotePCGroup);
    remotePCLa_13 = new QLabel(QStringLiteral("GPU時脈"), remotePCGroup);
    remotePCLa_14 = new QLabel(QStringLiteral("Hz"), remotePCGroup);
    remotePCLa_15 = new QLabel(QStringLiteral("Memory使用率"), remotePCGroup);
    remotePCLa_16 = new QLabel(QStringLiteral("%"), remotePCGroup);
    remotePCLa_17 = new QLabel(QStringLiteral("Desk使用率"), remotePCGroup);
    remotePCLa_18 = new QLabel(QStringLiteral("%"), remotePCGroup);
    remotePCLa_19 = new QLabel(QStringLiteral("網路使用量"), remotePCGroup);
    remotePCLa_20 = new QLabel(QStringLiteral("Mbps"), remotePCGroup);

    remotePCLa_02->setFont(*font);
    remotePCLa_03->setFont(*font);
    remotePCLa_04->setFont(*font);
    remotePCLa_05->setFont(*font);
    remotePCLa_06->setFont(*font);
    remotePCLa_07->setFont(*font);
    remotePCLa_08->setFont(*font);
    remotePCLa_09->setFont(*font);
    remotePCLa_10->setFont(*font);
    remotePCLa_11->setFont(*font);
    remotePCLa_12->setFont(*font);
    remotePCLa_13->setFont(*font);
    remotePCLa_14->setFont(*font);
    remotePCLa_15->setFont(*font);
    remotePCLa_16->setFont(*font);
    remotePCLa_17->setFont(*font);
    remotePCLa_18->setFont(*font);
    remotePCLa_19->setFont(*font);
    remotePCLa_20->setFont(*font);

    remoteItem = new QSpacerItem(20, 100, QSizePolicy::Minimum, QSizePolicy::Fixed);
    repclasp_01 = new QSpacerItem(100, 20,QSizePolicy::Fixed, QSizePolicy::Minimum);
    repclasp_02 = new QSpacerItem(37, 20,QSizePolicy::Fixed, QSizePolicy::Minimum);
    repclasp_03 = new QSpacerItem(53, 20,QSizePolicy::Fixed, QSizePolicy::Minimum);
    repclasp_04 = new QSpacerItem(53, 20,QSizePolicy::Fixed, QSizePolicy::Minimum);
    repclasp_05 = new QSpacerItem(36, 20,QSizePolicy::Fixed, QSizePolicy::Minimum);
    repclasp_06 = new QSpacerItem(52, 20,QSizePolicy::Fixed, QSizePolicy::Minimum);
    repclasp_07 = new QSpacerItem(52, 20,QSizePolicy::Fixed, QSizePolicy::Minimum);
    repclasp_08 = new QSpacerItem(5, 20,QSizePolicy::Fixed, QSizePolicy::Minimum);
    repclasp_09 = new QSpacerItem(33, 20,QSizePolicy::Fixed, QSizePolicy::Minimum);
    repclasp_10 = new QSpacerItem(38, 20,QSizePolicy::Fixed, QSizePolicy::Minimum);

    remoteLCD_01 = new QLCDNumber(remotePCGroup);
    remoteLCD_02 = new QLCDNumber(remotePCGroup);
    remoteLCD_03 = new QLCDNumber(remotePCGroup);
    remoteLCD_04 = new QLCDNumber(remotePCGroup);
    remoteLCD_05 = new QLCDNumber(remotePCGroup);
    remoteLCD_06 = new QLCDNumber(remotePCGroup);
    remoteLCD_07 = new QLCDNumber(remotePCGroup);
    remoteLCD_08 = new QLCDNumber(remotePCGroup);
    remoteLCD_09 = new QLCDNumber(remotePCGroup);

    remoteLCD_01->setDigitCount(5);
    remoteLCD_01->setMode(QLCDNumber::Dec);
    remoteLCD_01->setSegmentStyle(QLCDNumber::Flat);
    remoteLCD_02->setDigitCount(5);
    remoteLCD_02->setMode(QLCDNumber::Dec);
    remoteLCD_02->setSegmentStyle(QLCDNumber::Flat);
    remoteLCD_03->setDigitCount(5);
    remoteLCD_03->setMode(QLCDNumber::Dec);
    remoteLCD_03->setSegmentStyle(QLCDNumber::Flat);
    remoteLCD_04->setDigitCount(5);
    remoteLCD_04->setMode(QLCDNumber::Dec);
    remoteLCD_04->setSegmentStyle(QLCDNumber::Flat);
    remoteLCD_05->setDigitCount(5);
    remoteLCD_05->setMode(QLCDNumber::Dec);
    remoteLCD_05->setSegmentStyle(QLCDNumber::Flat);
    remoteLCD_06->setDigitCount(5);
    remoteLCD_06->setMode(QLCDNumber::Dec);
    remoteLCD_06->setSegmentStyle(QLCDNumber::Flat);
    remoteLCD_07->setDigitCount(5);
    remoteLCD_07->setMode(QLCDNumber::Dec);
    remoteLCD_07->setSegmentStyle(QLCDNumber::Flat);
    remoteLCD_08->setDigitCount(5);
    remoteLCD_08->setMode(QLCDNumber::Dec);
    remoteLCD_08->setSegmentStyle(QLCDNumber::Flat);
    remoteLCD_09->setDigitCount(5);
    remoteLCD_09->setMode(QLCDNumber::Dec);
    remoteLCD_09->setSegmentStyle(QLCDNumber::Flat);

    repclay_01->addWidget(remotePCLa_01);
    repclay_01->addItem(repclasp_01);
    repclay_01->addWidget(state);
    repclay_02->addWidget(remotePCLa_03);
    repclay_02->addItem(repclasp_02);
    repclay_02->addWidget(remoteLCD_01);
    repclay_02->addWidget(remotePCLa_04);
    repclay_03->addWidget(remotePCLa_05);
    repclay_03->addItem(repclasp_03);
    repclay_03->addWidget(remoteLCD_02);
    repclay_03->addWidget(remotePCLa_06);
    repclay_04->addWidget(remotePCLa_07);
    repclay_04->addItem(repclasp_04);
    repclay_04->addWidget(remoteLCD_03);
    repclay_04->addWidget(remotePCLa_08);
    repclay_05->addWidget(remotePCLa_09);
    repclay_05->addItem(repclasp_05);
    repclay_05->addWidget(remoteLCD_04);
    repclay_05->addWidget(remotePCLa_10);
    repclay_06->addWidget(remotePCLa_11);
    repclay_06->addItem(repclasp_06);
    repclay_06->addWidget(remoteLCD_05);
    repclay_06->addWidget(remotePCLa_12);
    repclay_07->addWidget(remotePCLa_13);
    repclay_07->addItem(repclasp_07);
    repclay_07->addWidget(remoteLCD_06);
    repclay_07->addWidget(remotePCLa_14);
    repclay_08->addWidget(remotePCLa_15);
    repclay_08->addItem(repclasp_08);
    repclay_08->addWidget(remoteLCD_07);
    repclay_08->addWidget(remotePCLa_16);
    repclay_09->addWidget(remotePCLa_17);
    repclay_09->addItem(repclasp_09);
    repclay_09->addWidget(remoteLCD_08);
    repclay_09->addWidget(remotePCLa_18);
    repclay_10->addWidget(remotePCLa_19);
    repclay_10->addItem(repclasp_10);
    repclay_10->addWidget(remoteLCD_09);
    repclay_10->addWidget(remotePCLa_20);

    remotePCLay->addLayout(repclay_01);
    remotePCLay->addWidget(remotePCLa_02);
    remotePCLay->addLayout(repclay_02);
    remotePCLay->addLayout(repclay_03);
    remotePCLay->addLayout(repclay_04);
    remotePCLay->addLayout(repclay_05);
    remotePCLay->addLayout(repclay_06);
    remotePCLay->addLayout(repclay_07);
    remotePCLay->addLayout(repclay_08);
    remotePCLay->addLayout(repclay_09);
    remotePCLay->addLayout(repclay_10);
    remotePCLay->addItem(remoteItem);

    remoteMain->addWidget(remotePCGroup);
}
